version: "2"
services:
  webserver:
    image: "nginx:alpine"
    volumes:
      - "./:/var/www"
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/"
      - ./storage/logs/:/var/log/nginx
    ports:
      - "8080:80"
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - "./:/var/www"
    working_dir: /var/www
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    ports:
      - "3388:3306"
    volumes:
      - "./docker/mysql/conf.d/:/etc/mysql/conf.d/"
      - "./docker-volumes-data/db:/var/lib/database"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    volumes:
      - "./docker-volumes-data/redis:/data"
